### ISSUE TITLE
Docs not deploying

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJBase.jl#482]
It seems the docs do not deploy after switching ci to gh actions. Is there a clue here in the actions log?

<img width="812" alt="Screen Shot 2020-12-01 at 6 18 24 PM" src="https://user-images.githubusercontent.com/30517088/100700224-d3535e80-3401-11eb-91d9-ed01b29f9df0.png">

**Comment by DilumAluthge** [comment]
That just means that pull request previews are not deployed.

Do you want to deploy pull request previews?

**Comment by DilumAluthge** [comment]
Ahhhh I found the issue. Completely different. I'll open a PR in a minute.

**Comment by DilumAluthge** [comment]
Should be fixed by https://github.com/alan-turing-institute/MLJBase.jl/pull/483

**Comment by ablaom** [comment]
I still don't see my documentation updates appearing in gh-pages. I also still see a ❌ next to "deploying" in the log:

<img width="722" alt="Screen Shot 2020-12-02 at 1 48 57 PM" src="https://user-images.githubusercontent.com/30517088/100813910-54176680-34a5-11eb-9e3d-782e69ed00e3.png">

When I check the deployment key "DOCUMENTER_KEY" in repo settings, it states that it has never been used. Perhaps this is a clue. 

I will try generating new rsa pair and see if that helps. 

cc @DilumAluthge

**Comment by ablaom** [comment]
BTW the first paragraph in the updated docs has been lengthened and reads:

[MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/) (Machine
Learning in Julia) is a toolbox written in Julia providing a common
interface and meta-algorithms for selecting, tuning, evaluating,
composing and comparing machine learning models written in Julia and
other languages.

**Comment by DilumAluthge** [comment]
Have you merged to master yet? You won't see any change until you merge to master

**Comment by ablaom** [comment]
Yeah. Merged to master

**Comment by DilumAluthge** [comment]
Try merging to master again now that we've fixed some stuff in the CI workflow file.

**Comment by ablaom** [comment]
Okay #489

**Comment by ablaom** [comment]
Some hours later this had made no difference. The new docs have not deployed to gh pages. Somewhere we need `Deploying ✔️ ` in the ci logs, no? I don't see that anywhere; only `Deploying ❌ `. https://github.com/alan-turing-institute/MLJBase.jl/issues/482#issuecomment-736915758

**Comment by ablaom** [comment]
For comparison, here's the most recent travis log (same version of Documenter):

![Uploading Screen Shot 2020-12-03 at 8.57.25 AM.png…]()

**Comment by DilumAluthge** [comment]
Looking at the most recent documentation build in master: https://github.com/alan-turing-institute/MLJBase.jl/runs/1488985044

Looks like the docs did deplo.

**Comment by ablaom** [comment]
Yeah I set `push_preview=true` b/s this is indeed required in special case of github actions (if you read the log carefully, it says this). But I'm still not *seeing* the doc updates when I go to gh-pages https://alan-turing-institute.github.io/MLJBase.jl/stable/ . Maybe I need to tag a new release?? (I never needed to with travis) Or maybe its an RSA issue:

<img width="844" alt="Screen Shot 2020-12-03 at 12 56 24 PM" src="https://user-images.githubusercontent.com/30517088/100945985-40cccf80-3567-11eb-9798-5227bce9c73e.png">

I'm pretty sure I set the keys correctly

**Comment by DilumAluthge** [comment]
> But I'm still not _seeing_ the doc updates when I go to gh-pages https://alan-turing-institute.github.io/MLJBase.jl/stable/ . Maybe I need to tag a new release??

So, if you want to see the doc updates without tagging a new release, you need to go to https://alan-turing-institute.github.io/MLJBase.jl/dev/ 

If you go to https://alan-turing-institute.github.io/MLJBase.jl/dev/ do you see the doc updates?

The way people usually do it is:
- https://alan-turing-institute.github.io/MLJBase.jl/dev/ - this will be the latest docs on master
- https://alan-turing-institute.github.io/MLJBase.jl/stable/ - this always points to the docs for the latest tagged release

**Comment by ablaom** [comment]
> So, if you want to see the doc updates without tagging a new release, you need to go to https://alan-turing-institute.github.io/MLJBase.jl/dev/

Nope. Not up-to-date

> The way people usually do it is:

Yeah, that will work here but we have to do it differently in MLJ because it combines documentation of multiple repositories with their own versioning.

**Comment by DilumAluthge** [comment]
Can you share a screenshot of the docs page that is not up-to-date for you?

**Comment by DilumAluthge** [comment]
> Yeah, that will work here but we have to do it differently in MLJ because it combines documentation of multiple repositories with their own versioning.

Oh geez yeah that makes things harder.

**Comment by ablaom** [comment]
The last word of first paragraph should be "languages" not "including:"

**Comment by DilumAluthge** [comment]
This is what I see:

<img width="771" alt="Screen Shot 2020-12-02 at 19 09 56" src="https://user-images.githubusercontent.com/5619885/100946739-e64a5980-34fb-11eb-8d13-a03e5ba4d130.png">

**Comment by ablaom** [comment]
No my bad. The dev is up-to-date Hooray!!

**Comment by DilumAluthge** [comment]
A combination of:
1. Local browser caching on your computer - maybe try clearing your browser cache, cookies, local storage, etc. You can also try opening a different browser, and/or opening an incognito window.
2. GitHub CDN does a lot of caching. We're in different parts of the world, so perhaps your GitHub CDN server is behind, but my GitHub CDN server is ahead.

**Comment by DilumAluthge** [comment]
FYI you can turn `push_preview` off and it should still work.

**Comment by ablaom** [comment]
I will roll this out to the other repo tomorrow. I'm in the middle of a tricky project just now. So much for your help.
